Docker support
PhantomBot/PhantomBot pull request #1294
Opened 2017-03-07 01:19 UTC by Hackebein

Added Docker files
Added load from environment functionality

2017-03-15 20:35 UTC, IllusionaryOne commented
I thought I had asked some questions, but let me see if they save this time!

Not sure the movement of the configuration is a good idea when folks are used to it in one place.  Is there a compelling reason to move it out?  

Has this been tested against non-Docker configurations and all of the OSs that we support as well to ensure it works properly?

Do not remove defaults that are created in the file.  Yes, they are superfluous in a way, but this way the user sees the configuration values.  We simply try to ensure that no matter what they are set later. 

No try/catch around method call that can throw Exceptions.

2017-03-20 10:49 UTC, Hackebein commented
The Configuration is no longer moved.

I tested it on Linux (Ubuntu, Debian) and Windows, Working like the same way.
I think "startProperties.setProperty" calls are obsolet, because in a config all variables or non defaults. I revert it later of the day. Same for try/catch, i miss there are 2 different Exceptions.

2017-04-02 15:10 UTC, Hackebein commented
All done for automated docker builds

example docker repo: https://hub.docker.com/r/hackebein/phantombot/

My Automated Build Configuration:
```
Build Settings: (checked) When active, builds will happen automatically on pushes.
```
```
Type "Branch"
Name "master"
Dockerfile Location "/"
Docker Tag Name "latest"
```
```
Type "Tag"
Name "/^v[0-9.]+/"
Dockerfile Location "/"
Docker Tag Name ""
```
```
Repository Links: openjdk
```

2017-04-13 16:57 UTC, kojitsari commented
Appears like you've met IO's requirements (from the brief look I've taken). I'll give him a ping next time he pops online about taking a look at this.

Sorry for the delay, most of us are having work and other life things slamming our free time right now.

2017-04-20 02:10 UTC, BrandenB requested changes

2017-04-20 02:10 UTC, ScaniaTV commented on Dockerfile
> +    && mv "${BASEDIR}/config" "${DATADIR}/" \
Config file has been removed since it was not needed.

2017-04-20 02:10 UTC, ScaniaTV commented on Dockerfile
> +    && ln -s "${DATADIR}/config" \
Config file has been removed since it was not needed.

2017-04-20 02:10 UTC, ScaniaTV commented on source/me/mast3rplan/phantombot/PhantomBot.java
> +                com.gmt2001.Console.out.println("Load configuration from File");
This will just spam the console, it's not needed.

2017-04-20 02:10 UTC, ScaniaTV commented on source/me/mast3rplan/phantombot/PhantomBot.java
> +                com.gmt2001.Console.out.println("Load " + Key + " from environment");
This will just spam the console, it's not needed.

2017-04-20 02:27 UTC, Hackebein commented
all review changes done

2017-05-05 16:19 UTC, BrandenB approved these changes

2017-05-05 16:19 UTC, ScaniaTV commented
I'm going to merge this, I assume you've tested it all.

2017-05-05 16:19 UTC, merged