Added subscriptionGift to subscribeHandler
PhantomBot/PhantomBot pull request #1765
Opened 2017-11-26 01:28 UTC by JustAlixe

Added subscriptionGift to subscribeHandler on twitches end will work on discord next :)

2017-11-26 02:04 UTC, ScaniaTV commented
**Issues:**
- No way to set a reward for the user who gifted the subscription.
- No commands to change these new settings.

2017-11-26 02:06 UTC, JustAlixe commented
ok ill get them done then push it to this pull request

2017-11-26 02:50 UTC, JustAlixe commented
There commands made and added a setting for the reward for the gifter

2017-11-26 17:32 UTC, ScaniaTV commented
Did you test this? I don't see any code adding the reward to the user who gave the subscription, also the `!giftsubwelcometoggle` command isn't using the right key in the database. Please be sure to test everything. 

Thanks.

2017-11-27 15:53 UTC, JustAlixe commented
Fixed sorry i forgot to add that whn i added the customization for it thansk for letting me know also hopw could i test this as im not an affilate or partner

2017-11-28 01:39 UTC, BrandenB requested changes
Please test everything like I mentioned before. This is clearly not fully tested. Just run commands, or send fake events from the core if you want to test everything, or read your code over and over again.

2017-11-28 01:39 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +            reSubReward = parseInt(action);
This should be `giftSubReward` and not `reSubReward `.

2017-11-28 01:39 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +            giftSubMessage = argsString ;
Remove the extra space after `argsString`.

2017-11-28 01:39 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +            $.setIniDbBoolean('subscribeHandler', 'reSubscriberWelcomeToggle', giftSubWelcomeToggle);
The key should be `giftSubWelcomeToggle` and not `reSubscriberWelcomeToggle`.

2017-11-28 08:25 UTC, JustAlixe commented
How do i send fake events ? im new to all that stuff but i fixed them 3 things you mentioned

2017-11-29 17:31 UTC, ScaniaTV commented
Simple usage of Rhino can accomplish this.

`Packages.tv.phantombot.event.EventBus.instance().post(EVENT_PACKAGE_HERE)`

2017-11-29 17:39 UTC, JustAlixe commented
If you like you can close this and ill just wait until you guys do it then update :)

2017-11-30 21:22 UTC, BrandenB approved these changes

2017-11-30 21:22 UTC, merged