Added a coolDownAnnounce function
PhantomBot/PhantomBot pull request #1840
Opened 2018-01-23 04:25 UTC by AlixeAtTwitch

I have added a toggleable message for when the adventure is able to be ran again!

![toggle for the pannel](https://www.alixe.pro/share/img/firefox_035212359S230118.png)
![command thats ran to toggle the cooldown announcement](http://alixe.pro/share/img/firefox_0414042710230118.png)
![output after the cooldown has ended](https://www.alixe.pro/share/img/firefox_035300844d230118.png)

**You may delete this note from your Pull Request if you so desire. It is acceptable if you leave it in place.**

2018-01-23 04:30 UTC, BrandenB requested changes

2018-01-23 04:30 UTC, ScaniaTV commented on javascript-source/games/adventureSystem.js
> +            }, coolDown);
Add `*1000` here or the cooldown will be in milliseconds.

2018-01-25 17:24 UTC, AlixeAtTwitch commented
@IllusionaryOne Any chance you can have a look and see if this is how it should be :)

2018-01-25 17:57 UTC, IllusionaryOne commented
This looks good to me.  If @ScaniaTV is good to sign off, and the changes he requested look good to him, then we can merge.

As a side note, we are implementing two developer reviews and two developer sign offs now on our end.

Cheers!

2018-01-25 20:46 UTC, ScaniaTV commented
Looks good here too, merging! Thanks!

2018-01-25 20:46 UTC, BrandenB approved these changes

2018-01-25 20:46 UTC, merged