Dakoda plays anonymous
PhantomBot/PhantomBot pull request #2101
Opened 2019-01-04 02:08 UTC by DakodaPlays

*changes*
* Added giftAnonSubMessage, massAnonGiftSubMessage, giftAnonSubWelcomeToggle and giftAnonSubWelcomeToggle Settings
* Added TwitchAnonymousSubscriptionGift and TwitchMassAnonymousSubscriptionGifted Binds
* Added giftanonsubwelcometoggle, massanongiftsubwelcometoggle, giftanonsubmessage and massanongiftsubmessage commands

**Note:** I would do tests but without a force event console command I cant :( if that can be added first I will test and show results before pushed

2019-01-04 11:32 UTC, BantomPhot commented
Typo in subscribeHandler.js -> `giftAnonSSubWelcomeToggle` (double S)

2019-01-04 19:57 UTC, IllusionaryOne commented
Throw this into ConsoleEventHandler.java and test.  I was able to compile with this so it must work.

```
import tv.phantombot.event.twitch.subscriber.TwitchMassAnonymousSubscriptionGiftedEvent;
import tv.phantombot.event.twitch.subscriber.TwitchAnonymousSubscriptionGiftEvent;



        /**
         * @consolecommand massanongiftsubtest - Test a mass anonymous gift subscription.
         */
        if (message.equalsIgnoreCase("anonsubgifttest")) {
            String userName = PhantomBot.generateRandomString(8);
            com.gmt2001.Console.out.println("Testing Mass Anonymous Gift Sub (Username = " + userName + ")");
            EventBus.instance().postAsync(new TwitchMassAnonymousSubscriptionGiftedEvent("10", "1000"));
            return;
        }

        /**
         * @consolecommand anonsubgifttest - Test an anonymous gift subscription
         */
        if (message.equalsIgnoreCase("anonsubgifttest")) {
            String userName = PhantomBot.generateRandomString(8);
            com.gmt2001.Console.out.println("Testing Anonymous Gift Sub (Username = " + userName + ")");
            EventBus.instance().postAsync(new TwitchAnonymousSubscriptionGiftEvent(userName, "1", "1000"));
            return;
        }
```

2019-01-04 20:40 UTC, DakodaPlays commented
@IllusionaryOne There I added a config and a command for !anonname

2019-01-04 20:41 UTC, BrandenB requested changes
After this is fixed I'll merge, thank you very much for doing this, saves me time.

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +                message = $.replace(message, '(name)', 'Anonymous viewer');
Here you can use `event.getUsername()`, it was added to the core's code, it will return `anonymous`.

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +        giftAnonSubMessage = $.getSetIniDbString('subscribeHandler', 'giftAnonSubMessage', '(name) just gifted (recipient) a subscription!'),
Here I would make the message the same as Twitch's, so it consists with the other default ones.

"An anonymous viewer gifted (recipient) a subscription!"

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +        massAnonGiftSubMessage = $.getSetIniDbString('subscribeHandler', 'massAnonGiftSubMessage', '(name) just gifted (amount) subscriptions to random users in the channel!'),
Same message as Twitch here as well.

"An anonymous viewer gifted (amount) subscriptions to random viewers!"

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +            if (message.match(/\(customemote\)/)) {
No need for this tag, it isn't a re-subscription.

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +                message = $.replace(message, '(name)', 'Anonymous viewer');
`event.getUsername()` here as well.

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +         * @commandpath giftanonsubwelcometoggle - Enable or disable subgifting alerts.
Update command description to `Enable or disable anonymous subgifting alerts.`

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +         * @commandpath massanongiftsubwelcometoggle - Enable or disable subgifting alerts.
Update command description `Enable or disable mass anonymous subgifting alerts.`

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +         * @commandpath giftanonsubmessage[message] - Set a message
Update spacing for parameter, and make the entire thing one line and update to message to `Set a message for anonymous gifting alerts.`

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
>           * @commandpath massgiftsubmessage [message] - Set a message for resubscribers.
This is on me, but if you can update it as well. 

`Set a message for gifting alerts.`

2019-01-04 20:41 UTC, ScaniaTV commented on javascript-source/handlers/subscribeHandler.js
> +         * @commandpath massanongiftsubmessage [message] - Set a message for resubscribers.
Command description update here too.

update to message to `Set a message for mass anonymous gifting alerts.`

2019-01-04 21:01 UTC, BrandenB approved these changes

2019-01-04 21:01 UTC, merged

2019-01-11 00:14 UTC, BantomPhot commented
Guys, add please `massgiftsubtest`, I have no permission to make a PR myself here.

Also `massanonsubgifttest` should be `massanongiftsubtest` instead, and `anonsubgifttest` should be `anongiftsubtest`, since there should be a consistency in the naming and unification with the existing command `giftsubtest`, imo. Otherwise there is a confusion and difficulty in remembering.

2019-01-12 08:36 UTC, IllusionaryOne commented
No, the naming convention is correct, it matches the Event itself which is what we want as development.  The purpose of the Console is for development testing, it just so happens that folks may also use it for testing in their stream.  It makes perfect sense to me knowing the name of the event.

massanonsubgifttest -> TwitchMassAnonymousSubscriptionGiftedEvent is the event.

2019-01-12 09:48 UTC, BantomPhot commented
That namings are a hell for perfectionists, LUL. Then there is only the request for mass gift sub command. I'll remind you later, if you don't mind.