Upgrade to Java_WebSocket_1.4.0
PhantomBot/PhantomBot pull request #2168
Opened 2019-07-19 09:55 UTC by gmt2001

Fixes infinite reconnect loop
Fixes thread sync failure that could lead to multiple connections being open
Fixes .mods output not being properly parsed
TwitchWSIRCParser is now a singleton
Reconnect is now protected from running multiple instances by Lock and boolean

2019-07-19 17:49 UTC, gmt2001 commented
Also did a bit of code cleanup in the areas I was working on in this PR

2019-07-24 21:29 UTC, ScaniaTV commented
Just to add details to this pull-request, this bug was found by a community I am apart of, after a few hours of testing gmt2001 and I found out that it was possible for the bot to open multiple reconnect threads, which could lead them to all connect at the same time (if a network outage happened in the middle) and open multiple connections to Twitch and send multiple of the same messages, I've tested this fix and it does work.

Merging so people can get the fix.

2019-07-24 21:38 UTC, BrandenB requested changes

2019-07-24 21:38 UTC, ScaniaTV commented on source/tv/phantombot/twitch/irc/TwitchWSIRCParser.java
> +        session.send(".mods");
.. rm this

2019-07-24 21:46 UTC, merged