Fix multi link exploit
PhantomBot/PhantomBot pull request #2212
Opened 2020-03-20 10:42 UTC by robsdedude

There is a potential exploit in the code.  
Suppose you have links moderated and "clips.twitch.tv" on your whitelist. If someone now sends a message like "evil.link.example.com oh, and also clips.twitch.tv", it wouldn't get moderated because one of the links is on the whiteList.

I am really sorry, but I couldn't get this project to build so I teste the my modifications stand-alone with nodejs. I know this project is running Rhino, but as said, after hours of fiddling around I gave up. Here's what I tested in nodejs:

```var linksRe = new RegExp('((?:(http|https|rtsp):\\/\\/(?:(?:[a-z0-9\\$\\-\\_\\.\\+\\!\\*\\\'\\(\\)' + '\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,64}(?:\\:(?:[a-z0-9\\$\\-\\_' + '\\.\\+\\!\\*\\\'\\(\\)\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,25})?\\@)?)?' + '((?:(?:[a-z0-9][a-z0-9\\-]{0,64}\\.)+' + '(?:' + '(?:aero|a[cdefgilmnoqrstuwxz])' + '|(?:biz|bike|bot|b[abdefghijmnorstvwyz])' + '|(?:com|c[acdfghiklmnoruvxyz])' + '|d[ejkmoz]' + '|(?:edu|e[cegrstu])' + '|(?:fyi|f[ijkmor])' + '|(?:gov|g[abdefghilmnpqrstuwy])' + '|(?:how|h[kmnrtu])' + '|(?:info|i[delmnoqrst])' + '|(?:jobs|j[emop])' + '|k[eghimnrwyz]' + '|l[abcikrstuvy]' + '|(?:mil|mobi|moe|m[acdeghklmnopqrstuvwxyz])' + '|(?:name|net|n[acefgilopruz])' + '|(?:org|om)' + '|(?:pro|p[aefghklmnrstwy])' + '|qa' + '|(?:r[eouw])' + '|(?:s[abcdeghijklmnortuvyz])' + '|(?:t[cdfghjklmnoprtvwz])' + '|u[agkmsyz]' + '|(?:vote|v[ceginu])' + '|(?:xxx)' + '|(?:watch|w[fs])' + '|y[etu]' + '|z[amw]))' + '|(?:(?:25[0-5]|2[0-4]' + '[0-9]|[0-1][0-9]{2}|[1-9][0-9]|[1-9])\\.(?:25[0-5]|2[0-4][0-9]' + '|[0-1][0-9]{2}|[1-9][0-9]|[1-9]|0)\\.(?:25[0-5]|2[0-4][0-9]|[0-1]' + '[0-9]{2}|[1-9][0-9]|[1-9]|0)\\.(?:25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}' + '|[1-9][0-9]|[0-9])))' + '(?:\\:\\d{1,5})?)' + '(\\/(?:(?:[a-z0-9\\;\\/\\?\\:\\@\\&\\=\\#\\~' + '\\-\\.\\+\\!\\*\\\'\\(\\)\\,\\_])|(?:\\%[a-fA-F0-9]{2}))*)?' + '(?:\\b|$)' + '|(\\.[a-z]+\\/|magnet:\/\/|mailto:\/\/|ed2k:\/\/|irc:\/\/|ircs:\/\/|skype:\/\/|ymsgr:\/\/|xfire:\/\/|steam:\/\/|aim:\/\/|spotify:\/\/)', 'ig');
function hasLinks(message) {
    return linksRe.test(message);
}
function getLinks(message) {
    var matches = Array.from(message.matchAll(linksRe));
    return matches.map(function(m) { return m[0] });
}
function checkWhiteList(message) {
    var links = getLinks(message);
    for (i in whiteList) {
        for (j = 0; j < links.length; j++) {
            if (links[j].indexOf(whiteList[i]) !== -1) {
                links.splice(j--, 1);
            }
        }
        if (links.length === 0) {
            return true;
        }
    }
    return false;
}
whiteList = ['example.com']
checkWhiteList('http://example.com')
checkWhiteList('http://example.org')
checkWhiteList('http://example.com and http://example.org')
whiteList = ['example.com', 'example.org']
checkWhiteList('http://example.com')
checkWhiteList('http://example.org')
checkWhiteList('http://example.com and http://example.org')
```

While I'm at it, I hope you are aware that this method of checking for white-listed links is also not bulletproof. Imagine someone sending a link like `https://www.twitch.tv/myNiceChannel?whatever=whitelisted.example.com`. Most sites don't care about unknown url parameters. A similar attack would be possible using the url fragment (the part after the `#`).

2020-03-20 20:06 UTC, BrandenB requested changes

2020-03-20 20:06 UTC, BrandenB commented on javascript-source/core/patternDetector.js
> +        var matches = Array.from(event.getMessage().matchAll(patterns.link));
You're using `matchAll` which is a JavaScript function against a Java String object, this will cause issues.

2020-03-23 22:51 UTC, BrandenB approved these changes

2020-03-23 23:01 UTC, BrandenB commented
> While I'm at it, I hope you are aware that this method of checking for white-listed links is also not bulletproof. Imagine someone sending a link like https://www.twitch.tv/myNiceChannel?whatever=whitelisted.example.com. Most sites don't care about unknown url parameters. A similar attack would be possible using the url fragment (the part after the #).

We could update the regular expressing to throw out the part after the first `/` of the URL, or remove it manually if found while processing the message since it isn't really needed in our case. The logic should work fine if someone does something similar to this:

`google.com?something=whitelisted.google.ca`

----

Another question, any reason why your `getLinks` function uses this logic?
```
var matches = Array.from(message.matchAll(linksRe));
    return matches.map(function(m) { return m[0] });
```

vs.

```
return message.match(linksRe)
```

2020-03-24 09:56 UTC, robsdedude commented
Question 2: No, no reason. I changed it.
Question 1: How about something like this:
```javascript
function checkWhiteList(message) {
    function checkLink(link, whiteListItem) {
        var baseLink = link.match(/[^.]*[^/]*/)[0];
        return link.indexOf(whiteListItem) < baseLink.length;
    }

    var links = $.patternDetector.getLinks(message);
    for (i = 0; i < whiteList.length; i++) {
        for (j = 0; j < links.length; j++) {
            if (checkLink(links[j], whiteList[i])) {
                links.splice(j--, 1);
            }
        }
        if (links.length === 0) {
            return true;
        }
    }
    return false;
}
```

This will make sure, the match includes something before the first slash after the host.
In contrast, your idea would break supporting things like `example.com/anything/beneath/this_path`.

2020-04-10 02:16 UTC, BrandenB commented
This would work, however I will merge the current fix for now. You can open a new pull request with those changes if you wish to do so.

2020-04-10 02:16 UTC, merged