Anchor link whitelist matching at TLD
PhantomBot/PhantomBot pull request #2221
Opened 2020-04-20 13:14 UTC by robsdedude

As explained in #2212, the link current implementation of the links white list is still vulnerable in a sense that it, probably for most users unexpectedly, permits some links. 

Examples and tests can be found here: https://github.com/PhantomBot/PhantomBot/pull/2212#issuecomment-603141513

To clarify how this works: It makes sure that the TLD (e.g. `.com`) of the URL is part of the white-listed link match.

2020-04-24 21:05 UTC, gmt2001 approved these changes

2020-04-24 21:23 UTC, BrandenB commented on javascript-source/core/chatModerator.js
> +            var itemRe = RegExp(whiteListItem.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'), 'g');
I'm not sure if in NodeJS not using `new` on a class works, but in Rhino it will cause an error for sure.

2020-04-24 21:25 UTC, gmt2001 requested changes
Needs `new` for RegExp

2020-04-28 08:26 UTC, robsdedude commented
> Needs `new` for RegExp

oopsie. Done.

2020-04-29 14:35 UTC, gmt2001 approved these changes

2020-05-11 13:36 UTC, robsdedude commented
@BrandenB, anything else you want me to do?

2020-05-12 02:17 UTC, BrandenB approved these changes

2020-05-12 02:17 UTC, merged