Add toggle to disable checking names for quotes in the database
PhantomBot/PhantomBot pull request #2224
Opened 2020-04-27 23:13 UTC by jaredkotoff

Adds dropdown in the quote settings to disable strict checking of usernames. 
When disabled allows for any name to be used.  
Defaults to true 
![image](https://user-images.githubusercontent.com/3268576/80429881-f3d29d80-88a1-11ea-93b8-a011e5f806bf.png)
![image](https://user-images.githubusercontent.com/3268576/80429791-c128a500-88a1-11ea-9528-66c49abbb76f.png)

2020-04-29 14:38 UTC, gmt2001 requested changes
Recommend adding a chat command for this toggle as well

2020-04-29 22:55 UTC, jaredkotoff commented
> Recommend adding a chat command for this toggle as well

Let me know if you have suggestions on naming or output string text

2020-04-29 23:06 UTC, gmt2001 approved these changes

2020-05-12 02:18 UTC, BrandenB approved these changes

2020-05-12 02:18 UTC, merged