Remove getModuleIndex()
PhantomBot/PhantomBot pull request #2397
Opened 2020-10-08 21:09 UTC by CDHayden

**javascript-source/init.js**
As modules are added as properties of the array object the array has no length, nor can indexOf find any elements and thus will always return -1.

* Removed the getModuleIndex() function

2020-10-09 16:40 UTC, BrandenB commented
Please also remove the export of the function to the global $ API

2020-10-09 16:41 UTC, BrandenB requested changes
Remove export to global $ API.

2020-10-09 16:59 UTC, CDHayden commented
Good spot, done.

2020-10-10 00:06 UTC, gmt2001 approved these changes

2020-10-10 00:06 UTC, merged