WIP: Add external and hidden commands + add panel options for those and disabled commands
PhantomBot/PhantomBot pull request #2412
Opened 2020-11-03 19:43 UTC by robsdedude

Phantombot already supports disabling commands via `!disablecom` and `!enablecom`. This feature is now accessible through the web panels as well. Furthermore I added the option to hide commands so that they don't get listed with `!commands`. This helps to reduce clutter. Finally, I've added external commands. Those are commands that the bot does not handle but list under `!commands`. This can be helpful if you have other bots in chat but you don't want them to respond to the `!commands` command too. Workarounds for this feature already exist: either add a custom command with empty response or adjust the translation of the `!commands` command. Both seem like unclean hacks to me.

todo:
 - [ ] hide and disable aliases

2020-11-03 21:59 UTC, gmt2001 submitted a review, later dismissed

2020-11-03 21:59 UTC, gmt2001 commented on javascript-source/commands/customCommands.js
> +         * @commandpath hide [command] - Hide a command in the !commands list
Comment has wrong command name

2020-11-03 22:38 UTC, BrandenB requested changes
I personally don't want to see external commands under the custom command section, it should go under commands > external. No where else. Otherwize you end-up with a bunch of stuff under one tab that isn't related. 

There also needs to be a loading circle under the external commands like custom commands.

Also, under advanced, when adding or editing a command there should be a checkbox with the option to hide it from the commands list.

If the panel cannot do what all commands do it won't get merged.

Thanks.

2020-11-04 07:21 UTC, robsdedude commented
> I personally don't want to see external commands under the custom command section, it should go under commands > external. No where else. Otherwize you end-up with a bunch of stuff under one tab that isn't related.

Makes sense. I put it there initially because I thought if it gets disabled together with the custom commands module it makes sense to have it on the same page. But same applies to aliases and it's its own page too. I'll make it so.


> Also, under advanced, when adding or editing a command there should be a checkbox with the option to hide it from the commands list.

I am confused. I thought this is exactly what I've done?

> Also follow the panel standard JS code, don't create a bunch of functions everywhere. Functions should also be declared as
> `const functionName = function() {`

I'm not sure I understood that correctly. Adding helper functions is ok, when I assign them to a const like above or not?

> If the panel cannot do what all commands do it won't get merged.

Funfact: disabling and enabling commands is currently (latest stable) possible only via commands. This PR aims exactly at changing that + more features.

> Thanks.

Thanks for the fast an in-depth review.

2020-11-04 19:23 UTC, robsdedude commented
Added features for aliases, added some screenshots, split external commands to own page, and updated code style.

2020-11-05 01:55 UTC, BrandenB approved these changes
Looks good now, will let gmt go over it once more.


Thanks!

2020-11-05 01:58 UTC, gmt2001 approved these changes

2020-11-05 01:59 UTC, merged

2020-11-05 08:13 UTC, robsdedude commented
I just realized, that default commands (e.g. `!mods`) can be disabled via chat command `!disablecom !mods` as well. Still there is no way to do so via the web panel. Probably worth another PR.

2020-11-06 07:00 UTC, BrandenB commented
If you want to do it, go ahead we'll merge it.

2021-01-01 20:14 UTC, gmt2001 commented
closes gmt2001/PhantomBot-1#120