Emotes on alertpage
PhantomBot/PhantomBot pull request #2939
Opened 2022-10-06 21:09 UTC by radipiz

Hi, first time contributing. I've cleaned my code and created a hopefully comprehensive commit history.
You probably know the flying emotes from other proprietary overlays.

I've implemented the following features:
* [Alerts] Support to display emotes (local, Emoji, BTTV, FFZ, Twitch Native + animated v2 Emotes)
* [Alerts] Support to play multiple media at once or sequential
* [Alerts] Support to run macros triggering emotes, sounds or videos (currently there is no frontend or action implemented to define or trigger these; I'm using a ui which is about 80% finished but probably too much for this PR)

I've added the following libraries:
* [com.vdurmont.emoji-java](https://github.com/vdurmont/emoji-java) (MIT License)
* [Keyframes](https://github.com/Keyframes/Keyframes) (MIT License)
* [animate.style](https://animate.style/) (MIT License)

Regarding my changes:
* `javascript-source/handlers/emojiHandler.js`: Handler module to process emoji and triggers an event on alertspollsocket
* `javascript-source/handlers/emotesBttvHandler.js`: Handler module to process emotes from BTTV and triggers an event on alertspollsocket
* `javascript-source/handlers/emotesFfzHandler.js`: Handler module to process emotes from FFZ and triggers an event on alertspollsocket
* `javascript-source/handlers/emotesTwitchHandler.js`: Handler module to trigger an alert on alertspollsocket for emotes from Twitch 
* ` javascript-source/handlers/emotesHandler.js`: Added FFZ and BTTV emotes to build a local emote cache for fast detection in chat messages
* `resources/config/clips/quak.webm`: Some demo file that can be shown on alerts page (source internet, widely spread video clip)
* `resources/config/clips/quak.webm`: Some demo file that can be shown on alerts page (source: i drew it)
* `resources/web/alerts/css/animate.min.css`: animate.style framework for animations with css used for the flying emotes
* `resources/web/alerts/index.html`:  Added elements for playing videos and emotes (and reformatted the file)
* `resources/web/alerts/js/index.js`: 
   * Pulled some constants into variables to make them easier to use
   * Rewrote queue handling so it can process a greater variety of events and play them simultaneously
   * Added flying emotes feature
   * Added handling for video clips
   * Added a macro feature to let different events play as a little macro
 * `resources/web/alerts/js/keyframes.dist.js`: Keyframes resource file used to generate the animations with js and css
 * `resources/web/panel/index.html`: Added a configuration page on the panel to configure the emote handlers
     * emotesAndEmoji page allows to enable and disable certain providers
 * `source/com/gmt2001/PathValidator.java`: Added clips and emotes path to allowed paths so locally stored content can be served
 * `source/com/gmt2001/httpwsserver/HTTPWSServer.java`: Added clips and emotes path to allowed paths so locally stored content can be served
 * `source/com/gmt2001/httpwsserver/HttpSslRedirectHandler.java`: same
 * `source/tv/phantombot/httpserver/HTTPNoAuthHandler.java`: same
 * `source/tv/phantombot/event/emotes/EmotesCacheUpdatedEvent.java`: same
 * `source/tv/phantombot/panel/WsAlertsPollsHandler.java`
    * Added methods to send emotes event in different overloads
    * Added method to play a video clip
    * added a method to stop all playing
    * added a method to play a list of commands (macro)
    * changed `alertImage` and `triggerAudioPanel` to contain the `ignoreIsPlaying` flag (Someone on the Discord asked for such a feature and I casually implemented it)
 * `source/tv/phantombot/scripts/handler/EmojiProcessor.java`: Helper class to process emojis to their codepoints

I hope it's understandable and welcome what I did. Once this is accepted, I have another feature that is built on this base.
If you have questions or suggestions, just contact me. I'm also on the Discord server for short notices.

2022-10-06 22:13 UTC, gmt2001 requested changes
There were a few minor things that were triggered by lint

Also, can you confirm that this was tested on the latest bot _without_ using the `rhino_es6` option?

2022-10-06 22:13 UTC, gmt2001 commented on resources/web/alerts/js/index.js
> +        const uniqueId = `${Date.now()}${Math.random().toString(16).substr(2, 8)}`
Codacy Production / Codacy Static Code Analysis

resources/web/alerts/js/index.js#L388

Missing semicolon.

2022-10-06 22:13 UTC, gmt2001 commented on resources/web/alerts/js/index.js
> +        video.src = `${defaultPath}/${filename}`
Codacy Production / Codacy Static Code Analysis

resources/web/alerts/js/index.js#L514

Missing semicolon.

2022-10-06 22:13 UTC, gmt2001 commented on source/tv/phantombot/event/emotes/EmotesCacheUpdatedEvent.java
> +    private NativeObject bttvEmotes;
Codacy Production / Codacy Static Code Analysis

source/tv/phantombot/event/emotes/EmotesCacheUpdatedEvent.java#L28

Private field 'bttvEmotes' could be made final; it is only initialized in the declaration or constructor.

2022-10-06 22:13 UTC, gmt2001 commented on source/tv/phantombot/event/emotes/EmotesCacheUpdatedEvent.java
> +    private NativeObject ffzEmotes;
Codacy Production / Codacy Static Code Analysis

source/tv/phantombot/event/emotes/EmotesCacheUpdatedEvent.java#L45

Private field 'ffzEmotes' could be made final; it is only initialized in the declaration or constructor.

2022-10-06 22:13 UTC, gmt2001 commented on source/tv/phantombot/event/emotes/EmotesCacheUpdatedEvent.java
> +    public EmotesCacheUpdatedEvent(NativeObject bttvEmotes, NativeObject ffzEmotes) {
Codacy Production / Codacy Static Code Analysis

source/tv/phantombot/event/emotes/EmotesCacheUpdatedEvent.java#L47

It is a good practice to call super() in a constructor

2022-10-06 22:13 UTC, gmt2001 commented on resources/web/panel/pages/keywords/emotesAndEmoji.html
> +    Copyright (C) 2016-2021 phantombot.github.io/PhantomBot
Update Copyright to 2022

2022-10-06 22:13 UTC, gmt2001 commented on resources/web/panel/js/pages/keywords/emotesAndEmoji.js
> + * Copyright (C) 2016-2021 phantombot.github.io/PhantomBot
Update copyright to 2022

2022-10-06 22:13 UTC, gmt2001 commented on resources/web/panel/js/pages/keywords/emotesAndEmoji.js
> +page = {
Global variable declared, enclose local scoped code inside lambda function and explicitly export only as necessary
```
$(function () {
    //Code here
});
```

2022-10-06 22:13 UTC, gmt2001 commented on javascript-source/handlers/emojiHandler.js
> + * Copyright (C) 2016-2021 phantombot.github.io/PhantomBot
Update copyright to 2022

2022-10-06 22:13 UTC, gmt2001 commented on javascript-source/handlers/emojiHandler.js
> +    $.bind('initReady', function () {
Remove unused hooks

2022-10-08 12:12 UTC, radipiz commented
Good find with the Rhino ES5 engine! I was using Rhino ES6 before it was a configurable option. There are some hints that my code is older because I implemented it for myself back then and used it with my configuration for more than a year now.

I hope, I've now solved all the issues.

2022-10-08 15:54 UTC, gmt2001 approved these changes

2022-10-08 15:55 UTC, merged