[Feature] Multiple panel users
PhantomBot/PhantomBot pull request #3227
Opened 2023-05-14 18:10 UTC by Sartharon

### What it does
- Allows multiple users to log on to the panel
- Integrated botlogin.txt user by means of the `paneluser `and `panelpassword` properties
- Basic permission system
- Passwords are sent after running through a one way hash function
- No clear text passwords are saved 
- Management via the panel
- Integrated into the console (only basic functions)

### Other changes
- Channel name is shown on the dashboard
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/313b6e47-b4a2-4cd6-a41f-bb0283968f1a)
- The username and channel name are shown in the profile menu / user menu
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/cf19386a-cec2-48c2-9898-4c10c1823b57)
- `helpers.getModal()` additional override options:
blockClosing: boolean          // Overrides all methods to close the dialog other than using the buttons
removecancel: boolean          // Removes the "Cancel" button from the dialog
- `helpers.getConfirmDeleteModal()` introduction of override options:
deleteText: 'Delete',   // Overrides the text displayed on the "Delete" button
blockClosing: boolean   // Overrides all methods to close the dialog other than using the confirm button
 
### Considerations
I'm open to change these design choices if needed or requested.
- Web socket tokens are not unique to users. Depending on the assigned permissions, either the `webauth `or `webauthRO` token from the bot properties is uses. Further changes to `WsSharedRWTokenAuthenticationHandler.java` would be necessary to accommodate this.
- Phantombot database schema (key - value) has been used. Where the key is the username and the value is a JSON object
- Users do not have their own panel configuration values, thus are forced to use the ones set by the owner
### Limitations
- Poor permission enforcement due to missing server side rendering of the web page (no PHP or similar)
- Currently only `Full Access` and `Read Only` permission. Additions can be made here, but they require further work and can never really be truly enforced due to the full client side rendering
- No management via commands or twitch chat
- The channel logo is shown logo for every user as their "profile picture"

### Functions limited to the owner
The owner is the user defined in the botlogin.txt
- Bot Setup Page
- Bot OAuth Page
- Create new users
- Edit existing users (other than the user defined in the botlogin.txt)
- Reset a user's passwords
- Deleting a user
- Dashboard configuration (Dark Mode, Event sort order, show/hide twitch player, ...)
- Panel user dashboard
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/60404b01-8737-44ee-b698-b0a34c914837)

### Functions for everyone
- General panel access
- Web socket read token
- Password change option
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/ceb67bc7-d5aa-4e49-bd3d-8ba33c6e13fd)

### Additional functions for Full Access users
- Restart bot
- Full panel access (excluding panel user management)

### New user creation / login flow
1. A random (temporary) password is created and shown (bot panel and console)
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/d28f1415-3723-4219-8f9d-a53eec5520d6)
2. New user logs on using the temporary password
3. New user is required to change the password upon first logon
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/a90395cd-85f6-4c62-a20c-983096298fa1)
4. New user is forced to log out and sign in again with their new password
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/6a2556bf-99bd-4748-b589-2c7cd1bce20b)

2023-05-14 18:15 UTC, Sartharon commented
> devskim found more than 10 potential problems in the proposed changes. Check the [Files changed](/PhantomBot/PhantomBot/pull/3227/files) tab for more details.

Just the hashing framework which is used [Crypto-JS](https://github.com/brix/crypto-js?utm_source=cdnjs&utm_medium=cdnjs_link&utm_campaign=cdnjs_library)

2023-05-14 20:37 UTC, gmt2001 requested changes

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +        name = name + "="
Codacy: Missing semicolon.

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +    }
Codacy: Missing semicolon.

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +    }
Codacy: Missing semicolon.

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +    }
Codacy: Missing semicolon.

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +    }
Codacy: Missing semicolon.

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +                hours = (date.getHours().toString().length == 1) ? "0" + date.getHours() : date.getHours(),
Codacy: Use strict equals `===`.

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +                minutes = (date.getMinutes().toString().length == 1) ? "0" + date.getMinutes() : date.getMinutes(),
Codacy: Use strict equals `===`.

2023-05-14 20:37 UTC, gmt2001 commented on resources/web/panel/js/utils/helpers.js
> +                seconds = (date.getSeconds().toString().length == 1) ? "0" + date.getSeconds() : date.getSeconds();
Codacy: Use strict equals `===`.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUser.java
> +public class PanelUser {
Codacy: A class which only has private constructors should be final.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUser.java
> +    protected static enum Type {
Codacy: Unnecessary modifier 'static' on enum 'Type': nested enums are implicitly static.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUserHandler.java
> +    protected static final String PANELUSERTABLE = "panelUsers";
Codacy: Avoid protected fields in a final class.  Change to private or package access.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUserHandler.java
> +    public static enum PanelMessage {
Codacy: Unnecessary modifier 'static' on enum 'PanelMessage': nested enums are implicitly static.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUserHandler.java
> +        private PanelMessage(String message, boolean isError) {
Codacy: Unnecessary modifier 'private' on constructor 'PanelMessage(String, boolean)': enum constructors are implicitly private.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUserHandler.java
> +    public static enum Permission{
Codacy: Unnecessary modifier 'static' on enum 'Permission': nested enums are implicitly static.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUserHandler.java
> +        private Permission(int value, String displayName) {
Codacy: Unnecessary modifier 'private' on constructor 'Permission(int, String)': enum constructors are implicitly private.

2023-05-14 20:37 UTC, gmt2001 commented on source/tv/phantombot/panel/PanelUser/PanelUserHandler.java
> +        List<PanelUser> users = new ArrayList<PanelUser>();
Codacy: Explicit type arguments can be replaced by Diamond Operator.

2023-05-14 20:37 UTC, gmt2001 commented on source/com/gmt2001/httpwsserver/auth/HttpBasicAuthenticationHandler.java
> +        return PanelUserHandler.checkLogin(user, pass);
Need to `or` this. Class is used by others for non-standard logins

2023-05-14 20:37 UTC, gmt2001 commented on source/com/gmt2001/httpwsserver/auth/HttpBasicAuthenticationHandler.java
> +                return PanelUserHandler.checkLoginB64(auth, req.uri());
Need to `or` this. Class is used by others for non-standard logins

2023-05-14 20:37 UTC, gmt2001 commented on source/com/gmt2001/httpwsserver/auth/HttpBasicAuthenticationHandler.java
> +            return PanelUserHandler.checkLoginB64(auth.substring(6), req.uri());
Need to `or` this. Class is used by others for non-standard logins

2023-05-15 21:27 UTC, gmt2001 approved these changes

2023-05-15 21:28 UTC, gmt2001 approved these changes

2023-05-15 21:36 UTC, merged