Add option to clear command cooldowns on online event
PhantomBot/PhantomBot pull request #3264
Opened 2023-06-12 22:27 UTC by Sartharon

- Adds an option to clear active cooldowns on online event (Allows users to create "single use" commands which can only be used once per stream, even if they stream multiple times a day)
- Adds a command that clears all active cooldowns
- Adds a command that clears the active cooldowns of a specific command
- Refactors the `handleCoolCom`-function and the output messages to reduce code duplication and readability

![image](https://github.com/PhantomBot/PhantomBot/assets/572591/2388c605-cd94-43b5-9c07-6234d5f57fed)
![image](https://github.com/PhantomBot/PhantomBot/assets/572591/53569486-8cd3-4de1-8361-75c5cd6b7af0)

2023-06-12 22:35 UTC, Sartharon commented
Draft:
Cody changes will come tomorrow
Save missing after clearing cooldowns

2023-06-13 07:37 UTC, Sartharon commented
Not sure what Codacy means with `Delete ´..´`
Other warnings are about having to use new lines in the lang files ... I could do that for all the lang files if it's something that's wanted

2023-06-13 08:26 UTC, gmt2001 commented
Indents apparently. I disabled it

2023-06-13 08:27 UTC, Sartharon commented
> Indents apparently. I disabled it

I figured as much and redid them for the mentioned lines but no dice

2023-06-13 22:54 UTC, gmt2001 requested changes
Missing update task to set default `clearOnOnline` on existing cooldowns

2023-06-13 22:54 UTC, gmt2001 commented on javascript-source/core/commandCoolDown.js
> +    $.bind('twitchOnline', function () {
You should re-read this function

2023-06-13 22:54 UTC, gmt2001 commented on javascript-source/core/misc.js
> +            return true;
Test fail
```js
stringToBoolean('false') === false
```

2023-06-13 22:54 UTC, gmt2001 commented on javascript-source/core/misc.js
> +        if (string.equalsIgnoreCase('true') || string === '1') {
`TypeError: Property 'equalsIgnoreCase' does not exist on object 'someString'`

Use `$.equalsIgnoreCase(str)` instead for a safe implementation

2023-06-13 22:54 UTC, gmt2001 commented on javascript-source/core/misc.js
> +        if (string.equalsIgnoreCase('false') || string === '0') {
`TypeError: Property 'equalsIgnoreCase' does not exist on object 'someString'`

Use `$.equalsIgnoreCase(str)` instead for a safe implementation

2023-06-14 06:33 UTC, Sartharon commented on javascript-source/core/commandCoolDown.js
> +    $.bind('twitchOnline', function () {
God ... was I blind that evening
Thanks for the review

2023-06-14 07:21 UTC, Sartharon commented
### [Codacy](https://app.codacy.com/manual/PhantomBot/PhantomBot/commit?cid=742249942) detected an issue:
#### Message: `Generic Object Injection Sink`

    
#### Occurred on:
+ **Commit**:  f087a084f12ac0b6249cba07aa9af7d52d333ec6
+ **File**:    [javascript-source/core/commandCoolDown.js](https://github.com/PhantomBot/PhantomBot/blob/f087a084f12ac0b6249cba07aa9af7d52d333ec6/javascript-source/core/commandCoolDown.js)
+ **LineNum**: [331](https://github.com/PhantomBot/PhantomBot/blob/f087a084f12ac0b6249cba07aa9af7d52d333ec6/javascript-source/core/commandCoolDown.js#L331)
+ **Code**:    `cooldowns[command].globalTime = 0;`

    
#### Currently on:
+ **Commit**:  1bdeead08801c9d855bb5bc0ad0947ead308bff4
+ **File**:    [javascript-source/core/commandCoolDown.js](https://github.com/PhantomBot/PhantomBot/blob/1bdeead08801c9d855bb5bc0ad0947ead308bff4/javascript-source/core/commandCoolDown.js)
+ **LineNum**: [302](https://github.com/PhantomBot/PhantomBot/blob/1bdeead08801c9d855bb5bc0ad0947ead308bff4/javascript-source/core/commandCoolDown.js#L302)
   

Command is validated as best we can (it's not null nor undefined `L#289`). More info on how this would normally be resolved [here](https://stackoverflow.com/questions/51715616/how-to-fix-codacy-alert-generic-object-injection-sink)
Plus this is still in beta as stated by codacy:
> For this tool we are not yet meeting this standard but you can help us improve the docs

2023-06-14 09:05 UTC, gmt2001 approved these changes

2023-06-14 09:05 UTC, merged