Drastically speed up readfilerand transformer for large files
PhantomBot/PhantomBot pull request #3547
Opened 2024-10-18 21:15 UTC by Sartharon

As indicated on discord, the `readfilerand` transformer is rather inefficient as it relies on reading the whole file and passes it multiple times (as arguments) between multiple functions before finally returning a selected line.

This PR aims to speed up the selection by utilizing `RandomAccessFile` allowing a file to be randomly accessed

Example with test file with 1000000 lines (7.52MB) jumping throughout the whole range as expected

![image](https://github.com/user-attachments/assets/98adc6ec-54a7-4f73-b2e2-25a2a9d92bf1)

Very rudimentary speed test

-  Old Version: +/- 5.8 s
![image](https://github.com/user-attachments/assets/ca4b4020-21e1-4784-90f5-9920dc2e2623)
- New Version: +/- 7 ns
![image](https://github.com/user-attachments/assets/d4b25baf-3f0e-4e98-bc76-8ce21a5b100b)

2024-10-18 23:21 UTC, gmt2001 requested changes

2024-10-18 23:21 UTC, gmt2001 commented on source/com/gmt2001/JSFileSystem.java
> +        try {
Prefer try-with-resources

2024-10-19 11:09 UTC, Sartharon commented
Also added `0 byte` length (emtpy file) check to prevent `IOException` from being thrown when seeking empty files

2024-10-19 13:22 UTC, gmt2001 approved these changes

2024-10-19 13:25 UTC, merged